-- Таблица для натальных карт, рассчитанных в админке (не привязаны к пользователям).
-- Выполнять в основной БД приложения (MySQL), не в Supabase.
CREATE TABLE IF NOT EXISTS admin_natal_charts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  chartDate VARCHAR(50) NOT NULL,
  chartTime VARCHAR(50) NOT NULL,
  chartCity VARCHAR(255) NOT NULL,
  chartLatitude DECIMAL(10, 7) NOT NULL,
  chartLongitude DECIMAL(10, 7) NOT NULL,
  timezone DECIMAL(5, 2) NOT NULL,
  julianDay DECIMAL(20, 8) NOT NULL,
  sun DECIMAL(10, 6) NOT NULL,
  moon DECIMAL(10, 6) NOT NULL,
  mercury DECIMAL(10, 6) NOT NULL,
  venus DECIMAL(10, 6) NOT NULL,
  mars DECIMAL(10, 6) NOT NULL,
  jupiter DECIMAL(10, 6) NOT NULL,
  saturn DECIMAL(10, 6) NOT NULL,
  uranus DECIMAL(10, 6) NOT NULL,
  neptune DECIMAL(10, 6) NOT NULL,
  pluto DECIMAL(10, 6) NOT NULL,
  northNode DECIMAL(10, 6) NOT NULL,
  southNode DECIMAL(10, 6) NOT NULL,
  ascendant DECIMAL(10, 6) NOT NULL,
  midheaven DECIMAL(10, 6) NOT NULL,
  house1 DECIMAL(10, 6) NOT NULL,
  house2 DECIMAL(10, 6) NOT NULL,
  house3 DECIMAL(10, 6) NOT NULL,
  house4 DECIMAL(10, 6) NOT NULL,
  house5 DECIMAL(10, 6) NOT NULL,
  house6 DECIMAL(10, 6) NOT NULL,
  house7 DECIMAL(10, 6) NOT NULL,
  house8 DECIMAL(10, 6) NOT NULL,
  house9 DECIMAL(10, 6) NOT NULL,
  house10 DECIMAL(10, 6) NOT NULL,
  house11 DECIMAL(10, 6) NOT NULL,
  house12 DECIMAL(10, 6) NOT NULL,
  houseSystem VARCHAR(10) NOT NULL DEFAULT 'P',
  siderealTime DECIMAL(10, 6) NOT NULL,
  calculatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
